from .atomic_permissions import *

MASTER_ACCOUNT = [
    ACCOUNT_READ,
    ACCOUNT_CREATE,
    ACCOUNT_UPDATE,
    ACCOUNT_DELETE,
    ACCOUNT_PARENT_CREATE,
    ACCOUNT_PARENT_READ,
    ACCOUNT_PARENT_UPDATE,
    ACCOUNT_PARENT_DELETE,
]

MASTER_DESIGN = [
    DESIGN_READ,
    DESIGN_CREATE,
    DESIGN_UPDATE,
    DESIGN_DELETE,
    DESIGN_TYPE_READ,
    DESIGN_TYPE_CREATE,
    DESIGN_TYPE_UPDATE,
    DESIGN_TYPE_DELETE,
]

MASTER_PRODUCT = [
    PRODUCT_READ,
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
]

MASTER_SUPPLIER = [
    SUPPLIER_READ,
    SUPPLIER_CREATE,
    SUPPLIER_UPDATE,
    SUPPLIER_DELETE,
]

REPORTING = [
    DASHBOARD_READ,
    LEDGER_READ,
]

AUTH_PERMISSION = [
    PERMISSION_CREATE,
    PERMISSION_READ,
    PERMISSION_UPDATE,
    PERMISSION_DELETE,
]

AUTH_USER = [
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
]

AUTH_ROLE = [
    ROLE_CREATE,
    ROLE_READ,
    ROLE_UPDATE,
    ROLE_DELETE,
]

PROCESS_IMPORT = [
    IMPORT
]

PROCESS_PURCHASING = [
    PURCHASING_READ,
    PURCHASING_CREATE,
    PURCHASING_UPDATE,
    PURCHASING_DELETE,
]

PROCESS_COLOR_KITCHEN = [
    COLOR_KITCHEN_BATCH_READ,
    COLOR_KITCHEN_BATCH_CREATE,
    COLOR_KITCHEN_BATCH_UPDATE,
    COLOR_KITCHEN_BATCH_DELETE,
    COLOR_KITCHEN_ENTRY_READ,
    COLOR_KITCHEN_ENTRY_CREATE,
    COLOR_KITCHEN_ENTRY_UPDATE,
    COLOR_KITCHEN_ENTRY_DELETE,
]

PROCESS_STOCK_MOVEMENT = [
    STOCK_MOVEMENT_READ,
    STOCK_MOVEMENT_CREATE,
    STOCK_MOVEMENT_UPDATE,
    STOCK_MOVEMENT_DELETE,
]

PROCESS_STOCK_OPNAME = [
    STOCK_OPNAME_READ,
    STOCK_OPNAME_CREATE,
    STOCK_OPNAME_UPDATE,
    STOCK_OPNAME_DELETE,
]
