"""added opj

Revision ID: 14b1d9dfbab6
Revises: 725a603e9e9c
Create Date: 2025-12-08 18:40:07.512969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b1d9dfbab6'
down_revision: Union[str, None] = '725a603e9e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opjs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('no_dyeing', sa.String(), nullable=True),
    sa.Column('gs_grey', sa.String(), nullable=True),
    sa.Column('gs_jadi', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('printing_ink', sa.Enum('DISPERSE', 'REACTIVE', 'PIGMENT', name='printing_ink_enum'), nullable=False),
    sa.Column('jenis_kain', sa.String(), nullable=True),
    sa.Column('kode_kain', sa.String(), nullable=True),
    sa.Column('lebar', sa.Float(), nullable=True),
    sa.Column('repeat_gambar', sa.Float(), nullable=True),
    sa.Column('garis_potong', sa.Float(), nullable=True),
    sa.Column('folding', sa.Enum('YARD', 'GULUNG', name='folding_enum'), nullable=True),
    sa.Column('face_direction', sa.Enum('MUKA_KE_DALAM', 'MUKA_KE_LUAR', name='face_direction_enum'), nullable=True),
    sa.Column('pe_type', sa.Enum('PE_I_KRG_PE', 'PE_II_KRG_PE', name='pe_type_enum'), nullable=True),
    sa.Column('printing_machine', sa.Enum('ROTARY', 'FLAT', name='printing_machine_enum'), nullable=False),
    sa.Column('jumlah_warna', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('opj_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ground_color', sa.String(), nullable=False),
    sa.Column('roll', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('opj_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opj_id'], ['opjs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opj_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_type', sa.Enum('GREY', 'PERBAIKAN', 'PFP', 'OPTICWHITE', 'DYEING', 'PRINTING', 'SERBLEACH', 'RESINFINISH', name='opj_process_enum'), nullable=False),
    sa.Column('opj_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opj_id'], ['opjs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opj_processes')
    op.drop_table('opj_details')
    op.drop_table('opjs')
    # ### end Alembic commands ###
