"""update return to have quantity start and quantity end

Revision ID: 23f62ff01bdf
Revises: a75b2a18c051
Create Date: 2025-12-20 22:23:22.722008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f62ff01bdf'
down_revision: Union[str, None] = 'a75b2a18c051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TYPE opj_process_enum ADD VALUE IF NOT EXISTS 'PERBAIKAN'
    """)
    op.add_column('returns', sa.Column('quantity_start', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('returns', sa.Column('quantity_end', sa.Numeric(precision=18, scale=2), nullable=False))
    op.drop_column('returns', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returns', sa.Column('quantity', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
    op.drop_column('returns', 'quantity_end')
    op.drop_column('returns', 'quantity_start')
    # ### end Alembic commands ###
