"""added audit to all tables and user

Revision ID: 5e8032f1bd33
Revises: 8c1c7d194a3b
Create Date: 2025-11-12 14:06:44.149764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8032f1bd33'
down_revision: Union[str, None] = '8c1c7d194a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_login_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.add_column('account_parents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('account_parents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('account_parents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('account_parents', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('account_parents', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('account_parents', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account_parents', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'account_parents', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'account_parents', 'users', ['updated_by'], ['id'])
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('accounts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('accounts', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'accounts', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'accounts', 'users', ['deleted_by'], ['id'])
    op.add_column('color_kitchen_batch_details', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('color_kitchen_batch_details', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('color_kitchen_batch_details', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('color_kitchen_batch_details', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('color_kitchen_batch_details', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('color_kitchen_batch_details', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'color_kitchen_batch_details', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'color_kitchen_batch_details', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'color_kitchen_batch_details', 'users', ['deleted_by'], ['id'])
    op.add_column('color_kitchen_batches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('color_kitchen_batches', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('color_kitchen_batches', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('color_kitchen_batches', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('color_kitchen_batches', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('color_kitchen_batches', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'color_kitchen_batches', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'color_kitchen_batches', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'color_kitchen_batches', 'users', ['updated_by'], ['id'])
    op.add_column('color_kitchen_entries', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('color_kitchen_entries', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('color_kitchen_entries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('color_kitchen_entries', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('color_kitchen_entries', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('color_kitchen_entries', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'color_kitchen_entries', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'color_kitchen_entries', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'color_kitchen_entries', 'users', ['deleted_by'], ['id'])
    op.add_column('color_kitchen_entry_details', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('color_kitchen_entry_details', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('color_kitchen_entry_details', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('color_kitchen_entry_details', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('color_kitchen_entry_details', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('color_kitchen_entry_details', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'color_kitchen_entry_details', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'color_kitchen_entry_details', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'color_kitchen_entry_details', 'users', ['updated_by'], ['id'])
    op.add_column('design_types', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('design_types', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('design_types', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('design_types', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('design_types', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('design_types', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'design_types', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'design_types', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'design_types', 'users', ['deleted_by'], ['id'])
    op.add_column('designs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('designs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('designs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('designs', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('designs', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('designs', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'designs', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'designs', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'designs', 'users', ['created_by'], ['id'])
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    op.add_column('purchasing_details', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('purchasing_details', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchasing_details', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchasing_details', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('purchasing_details', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('purchasing_details', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchasing_details', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'purchasing_details', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'purchasing_details', 'users', ['created_by'], ['id'])
    op.add_column('purchasings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('purchasings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchasings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchasings', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('purchasings', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('purchasings', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchasings', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'purchasings', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'purchasings', 'users', ['deleted_by'], ['id'])
    op.add_column('stock_movement_details', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('stock_movement_details', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stock_movement_details', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stock_movement_details', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('stock_movement_details', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('stock_movement_details', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_movement_details', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'stock_movement_details', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'stock_movement_details', 'users', ['updated_by'], ['id'])
    op.add_column('stock_movements', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('stock_movements', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stock_movements', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stock_movements', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('stock_movements', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('stock_movements', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_movements', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'stock_movements', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'stock_movements', 'users', ['updated_by'], ['id'])
    op.add_column('stock_opname_details', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('stock_opname_details', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stock_opname_details', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stock_opname_details', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('stock_opname_details', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('stock_opname_details', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_opname_details', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'stock_opname_details', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'stock_opname_details', 'users', ['created_by'], ['id'])
    op.add_column('stock_opnames', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('stock_opnames', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stock_opnames', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stock_opnames', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('stock_opnames', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('stock_opnames', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_opnames', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'stock_opnames', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'stock_opnames', 'users', ['created_by'], ['id'])
    op.add_column('suppliers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('suppliers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('suppliers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('suppliers', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'suppliers', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'suppliers', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'deleted_by')
    op.drop_column('suppliers', 'updated_by')
    op.drop_column('suppliers', 'created_by')
    op.drop_column('suppliers', 'deleted_at')
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'created_at')
    op.drop_constraint(None, 'stock_opnames', type_='foreignkey')
    op.drop_constraint(None, 'stock_opnames', type_='foreignkey')
    op.drop_constraint(None, 'stock_opnames', type_='foreignkey')
    op.drop_column('stock_opnames', 'deleted_by')
    op.drop_column('stock_opnames', 'updated_by')
    op.drop_column('stock_opnames', 'created_by')
    op.drop_column('stock_opnames', 'deleted_at')
    op.drop_column('stock_opnames', 'updated_at')
    op.drop_column('stock_opnames', 'created_at')
    op.drop_constraint(None, 'stock_opname_details', type_='foreignkey')
    op.drop_constraint(None, 'stock_opname_details', type_='foreignkey')
    op.drop_constraint(None, 'stock_opname_details', type_='foreignkey')
    op.drop_column('stock_opname_details', 'deleted_by')
    op.drop_column('stock_opname_details', 'updated_by')
    op.drop_column('stock_opname_details', 'created_by')
    op.drop_column('stock_opname_details', 'deleted_at')
    op.drop_column('stock_opname_details', 'updated_at')
    op.drop_column('stock_opname_details', 'created_at')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'deleted_by')
    op.drop_column('stock_movements', 'updated_by')
    op.drop_column('stock_movements', 'created_by')
    op.drop_column('stock_movements', 'deleted_at')
    op.drop_column('stock_movements', 'updated_at')
    op.drop_column('stock_movements', 'created_at')
    op.drop_constraint(None, 'stock_movement_details', type_='foreignkey')
    op.drop_constraint(None, 'stock_movement_details', type_='foreignkey')
    op.drop_constraint(None, 'stock_movement_details', type_='foreignkey')
    op.drop_column('stock_movement_details', 'deleted_by')
    op.drop_column('stock_movement_details', 'updated_by')
    op.drop_column('stock_movement_details', 'created_by')
    op.drop_column('stock_movement_details', 'deleted_at')
    op.drop_column('stock_movement_details', 'updated_at')
    op.drop_column('stock_movement_details', 'created_at')
    op.drop_constraint(None, 'purchasings', type_='foreignkey')
    op.drop_constraint(None, 'purchasings', type_='foreignkey')
    op.drop_constraint(None, 'purchasings', type_='foreignkey')
    op.drop_column('purchasings', 'deleted_by')
    op.drop_column('purchasings', 'updated_by')
    op.drop_column('purchasings', 'created_by')
    op.drop_column('purchasings', 'deleted_at')
    op.drop_column('purchasings', 'updated_at')
    op.drop_column('purchasings', 'created_at')
    op.drop_constraint(None, 'purchasing_details', type_='foreignkey')
    op.drop_constraint(None, 'purchasing_details', type_='foreignkey')
    op.drop_constraint(None, 'purchasing_details', type_='foreignkey')
    op.drop_column('purchasing_details', 'deleted_by')
    op.drop_column('purchasing_details', 'updated_by')
    op.drop_column('purchasing_details', 'created_by')
    op.drop_column('purchasing_details', 'deleted_at')
    op.drop_column('purchasing_details', 'updated_at')
    op.drop_column('purchasing_details', 'created_at')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'deleted_by')
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'created_by')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_constraint(None, 'designs', type_='foreignkey')
    op.drop_constraint(None, 'designs', type_='foreignkey')
    op.drop_constraint(None, 'designs', type_='foreignkey')
    op.drop_column('designs', 'deleted_by')
    op.drop_column('designs', 'updated_by')
    op.drop_column('designs', 'created_by')
    op.drop_column('designs', 'deleted_at')
    op.drop_column('designs', 'updated_at')
    op.drop_column('designs', 'created_at')
    op.drop_constraint(None, 'design_types', type_='foreignkey')
    op.drop_constraint(None, 'design_types', type_='foreignkey')
    op.drop_constraint(None, 'design_types', type_='foreignkey')
    op.drop_column('design_types', 'deleted_by')
    op.drop_column('design_types', 'updated_by')
    op.drop_column('design_types', 'created_by')
    op.drop_column('design_types', 'deleted_at')
    op.drop_column('design_types', 'updated_at')
    op.drop_column('design_types', 'created_at')
    op.drop_constraint(None, 'color_kitchen_entry_details', type_='foreignkey')
    op.drop_constraint(None, 'color_kitchen_entry_details', type_='foreignkey')
    op.drop_constraint(None, 'color_kitchen_entry_details', type_='foreignkey')
    op.drop_column('color_kitchen_entry_details', 'deleted_by')
    op.drop_column('color_kitchen_entry_details', 'updated_by')
    op.drop_column('color_kitchen_entry_details', 'created_by')
    op.drop_column('color_kitchen_entry_details', 'deleted_at')
    op.drop_column('color_kitchen_entry_details', 'updated_at')
    op.drop_column('color_kitchen_entry_details', 'created_at')
    op.drop_constraint(None, 'color_kitchen_entries', type_='foreignkey')
    op.drop_constraint(None, 'color_kitchen_entries', type_='foreignkey')
    op.drop_constraint(None, 'color_kitchen_entries', type_='foreignkey')
    op.drop_column('color_kitchen_entries', 'deleted_by')
    op.drop_column('color_kitchen_entries', 'updated_by')
    op.drop_column('color_kitchen_entries', 'created_by')
    op.drop_column('color_kitchen_entries', 'deleted_at')
    op.drop_column('color_kitchen_entries', 'updated_at')
    op.drop_column('color_kitchen_entries', 'created_at')
    op.drop_constraint(None, 'color_kitchen_batches', type_='foreignkey')
    op.drop_constraint(None, 'color_kitchen_batches', type_='foreignkey')
    op.drop_constraint(None, 'color_kitchen_batches', type_='foreignkey')
    op.drop_column('color_kitchen_batches', 'deleted_by')
    op.drop_column('color_kitchen_batches', 'updated_by')
    op.drop_column('color_kitchen_batches', 'created_by')
    op.drop_column('color_kitchen_batches', 'deleted_at')
    op.drop_column('color_kitchen_batches', 'updated_at')
    op.drop_column('color_kitchen_batches', 'created_at')
    op.drop_constraint(None, 'color_kitchen_batch_details', type_='foreignkey')
    op.drop_constraint(None, 'color_kitchen_batch_details', type_='foreignkey')
    op.drop_constraint(None, 'color_kitchen_batch_details', type_='foreignkey')
    op.drop_column('color_kitchen_batch_details', 'deleted_by')
    op.drop_column('color_kitchen_batch_details', 'updated_by')
    op.drop_column('color_kitchen_batch_details', 'created_by')
    op.drop_column('color_kitchen_batch_details', 'deleted_at')
    op.drop_column('color_kitchen_batch_details', 'updated_at')
    op.drop_column('color_kitchen_batch_details', 'created_at')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'deleted_by')
    op.drop_column('accounts', 'updated_by')
    op.drop_column('accounts', 'created_by')
    op.drop_column('accounts', 'deleted_at')
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'created_at')
    op.drop_constraint(None, 'account_parents', type_='foreignkey')
    op.drop_constraint(None, 'account_parents', type_='foreignkey')
    op.drop_constraint(None, 'account_parents', type_='foreignkey')
    op.drop_column('account_parents', 'deleted_by')
    op.drop_column('account_parents', 'updated_by')
    op.drop_column('account_parents', 'created_by')
    op.drop_column('account_parents', 'deleted_at')
    op.drop_column('account_parents', 'updated_at')
    op.drop_column('account_parents', 'created_at')
    op.drop_table('user_role')
    op.drop_table('user_login_log')
    op.drop_table('role_permission')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
