"""update return to have roll

Revision ID: 9288f7cc0881
Revises: 23f62ff01bdf
Create Date: 2025-12-21 00:43:04.151812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9288f7cc0881'
down_revision: Union[str, None] = '23f62ff01bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returns', sa.Column('roll', sa.Numeric(precision=18, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('returns', 'roll')
    # ### end Alembic commands ###
