"""update opj process enum

Revision ID: a75b2a18c051
Revises: f0c57f5fd06a
Create Date: 2025-12-19 01:06:41.125745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75b2a18c051'
down_revision: Union[str, None] = 'f0c57f5fd06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        ALTER TYPE opj_process_enum ADD VALUE IF NOT EXISTS 'CUCI+FINISH'
    """)
    op.execute("""
        ALTER TYPE opj_process_enum ADD VALUE IF NOT EXISTS 'PROSES'
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
