"""create clients table final

Revision ID: b60094ff6110
Revises: 0bc90eafb612
Create Date: 2025-12-01 18:13:19.510882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b60094ff6110'
down_revision: Union[str, None] = '0bc90eafb612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
     op.create_table(
        'clients',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('phone_no', sa.String(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()')),
        sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('updated_by', sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('deleted_by', sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('clients', sa.Column('created_by', sa.Integer(), nullable=True))
    # op.add_column('clients', sa.Column('updated_by', sa.Integer(), nullable=True))
    # op.add_column('clients', sa.Column('deleted_by', sa.Integer(), nullable=True))
    # op.alter_column('clients', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            server_default=sa.text('now()'),
    #            existing_nullable=True)
    # op.create_foreign_key(None, 'clients', 'users', ['updated_by'], ['id'])
    # op.create_foreign_key(None, 'clients', 'users', ['deleted_by'], ['id'])
    # op.create_foreign_key(None, 'clients', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('clients')
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'clients', type_='foreignkey')
    # op.drop_constraint(None, 'clients', type_='foreignkey')
    # op.drop_constraint(None, 'clients', type_='foreignkey')
    # op.alter_column('clients', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            server_default=None,
    #            existing_nullable=True)
    # op.drop_column('clients', 'deleted_by')
    # op.drop_column('clients', 'updated_by')
    # op.drop_column('clients', 'created_by')
    # ### end Alembic commands ###
