"""create clients table final

Revision ID: b60094ff6110
Revises: 0bc90eafb612
Create Date: 2025-12-01 18:13:19.510882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b60094ff6110'
down_revision: Union[str, None] = '0bc90eafb612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_foreign_key(None, 'clients', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'clients', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'clients', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_column('clients', 'deleted_by')
    op.drop_column('clients', 'updated_by')
    op.drop_column('clients', 'created_by')
    # ### end Alembic commands ###
