"""add ppn to sales

Revision ID: cc9ab94f63c2
Revises: d7e56f7bca58
Create Date: 2025-12-12 15:35:23.601795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9ab94f63c2'
down_revision: Union[str, None] = 'd7e56f7bca58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('ppn', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'ppn')
    # ### end Alembic commands ###
