"""refactor opj

Revision ID: d7e56f7bca58
Revises: 2205dc983ec2
Create Date: 2025-12-10 21:08:15.157709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7e56f7bca58'
down_revision: Union[str, None] = '2205dc983ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create new enum type
    op.execute("CREATE TYPE process_condition_enum AS ENUM ('GREY', 'PERBAIKAN', 'PFP', 'OPTICWHITE', 'DYEING', 'PRINTING', 'SERBLEACH', 'RESINFINISH')")

    op.execute("""
        ALTER TABLE opj_processes
        ALTER COLUMN process_type
        TYPE process_condition_enum
        USING process_type::text::process_condition_enum
    """)

    op.execute("DROP TYPE opj_process_enum")
    
    # Recreate enum for printing ink usage
    op.execute("""
        CREATE TYPE opj_process_enum AS ENUM ('DISPERSE', 'REACTIVE', 'PIGMENT')
    """)

    # Now safe to add the column
    op.add_column(
        'opjs',
        sa.Column(
            'process_type',
            sa.Enum('DISPERSE', 'REACTIVE', 'PIGMENT', name='opj_process_enum'),
            nullable=False
        )
    )

    # Remove old column
    op.drop_column('opjs', 'printing_ink')
    op.add_column('returns', sa.Column('code', sa.String(), nullable=False))
    op.add_column('returns', sa.Column('opj_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'returns', 'opjs', ['opj_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

def downgrade() -> None:
    # 1. Recreate the OLD enum type
    op.execute("""
        CREATE TYPE opj_process_enum AS ENUM (
            'GREY', 'PERBAIKAN', 'PFP', 'OPTICWHITE',
            'DYEING', 'PRINTING', 'SERBLEACH', 'RESINFINISH'
        )
    """)

    # 2. Alter column to use OLD enum type again
    op.alter_column(
        'opj_processes',
        'process_type',
        existing_type=sa.Enum(
            'GREY', 'PERBAIKAN', 'PFP', 'OPTICWHITE',
            'DYEING', 'PRINTING', 'SERBLEACH', 'RESINFINISH',
            name='process_condition_enum'
        ),
        type_=postgresql.ENUM(
            'GREY', 'PERBAIKAN', 'PFP', 'OPTICWHITE',
            'DYEING', 'PRINTING', 'SERBLEACH', 'RESINFINISH',
            name='opj_process_enum'
        ),
        existing_nullable=False,
    )

    # 3. DROP the new enum type (safe because no columns reference it anymore)
    op.execute("DROP TYPE process_condition_enum")

    # 4. Restore removed columns
    op.add_column('opjs', sa.Column(
        'printing_ink',
        postgresql.ENUM('DISPERSE', 'REACTIVE', 'PIGMENT', name='printing_ink_enum'),
        nullable=False
    ))

    # 5. Remove the new column you added
    op.drop_column('opjs', 'process_type')

    # 6. DROP FK + remove changes to returns table
    op.drop_constraint(None, 'returns', type_='foreignkey')
    op.drop_column('returns', 'opj_id')
    op.drop_column('returns', 'code')

