"""ganti account_no di types.py ke string

Revision ID: ea6da9472869
Revises: dc1fc71ab06e
Create Date: 2025-11-20 13:51:41.943154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6da9472869'
down_revision: Union[str, None] = 'dc1fc71ab06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_parents', 'account_no',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_parents', 'account_no',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
