"""ck to opj

Revision ID: ebfd9e4c407b
Revises: 14b1d9dfbab6
Create Date: 2025-12-08 18:41:19.441417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfd9e4c407b'
down_revision: Union[str, None] = '14b1d9dfbab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color_kitchen_entries', sa.Column('opj_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'color_kitchen_entries', 'opjs', ['opj_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'color_kitchen_entries', type_='foreignkey')
    op.drop_column('color_kitchen_entries', 'opj_id')
    # ### end Alembic commands ###
