"""add discount to sales and roll to delivery

Revision ID: ed212d899161
Revises: e279fa0cec8c
Create Date: 2025-12-14 00:50:31.570705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed212d899161'
down_revision: Union[str, None] = 'e279fa0cec8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('roll', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('sales', sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=False))
    op.drop_constraint(op.f('sales_color_kitchen_id_fkey'), 'sales', type_='foreignkey')
    op.drop_column('sales', 'color_kitchen_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('color_kitchen_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sales_color_kitchen_id_fkey'), 'sales', 'color_kitchen_entries', ['color_kitchen_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('sales', 'discount')
    op.drop_column('deliveries', 'roll')
    # ### end Alembic commands ###
