"""sales to opj

Revision ID: f0a5a8bbb6c9
Revises: ebfd9e4c407b
Create Date: 2025-12-08 18:42:40.512493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a5a8bbb6c9'
down_revision: Union[str, None] = 'ebfd9e4c407b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('opj_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'opjs', ['opj_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'opj_id')
    # ### end Alembic commands ###
